### PR TITLE
Adding support for core.matrix PMatrixProducts protocol 

### PR DESCRIPTION
**Pull request by jlowenz**
Added inner/outer products for clatrix vector/matrix. Updated Clojure dependency to 1.8.0 (since I couldn't run tests without it).

### CODE REVIEW

**Comment by jlowenz** [comment]
The failed check looks like it has to do with JDK 6:

http://dev.clojure.org/jira/browse/CLJS-1220

**Comment by mikera** [comment]
Hi @jlowenz, thanks for the PR! Looks sensible but can you add some tests for the different possible dimensionalities?

I think we need to test at a minimum:
- vector \* vector
- scalar \* vector
- vector\* scalar
- vector \* matrix
- matrix \* vector
- matrix \* matrix

Results should be `equals` to whatever comes back from the `:persistent-vector` implementation

**Comment by jlowenz** [comment]
Hi @mikera, sorry it took a while (I thought I sent a message earlier), but the latest commit should address the issues. I found what looks like a bug in the persistent-vector implementation of outer-product in core.matrix; the current tests in this repo make modifications to the return values to match what should be the correct output... 

For example, since core.matrix is using `element-map` to prescale each element by the argument, a matrix-vector outer product yields a 3 dimensional array (a matrix-matrix product yields a 4D array!), but the Kronecker product (the generalization of outer product to matrices) specifies a 2 dimensional matrix (mp x nq) for an m x n and a p x q matrix.

I can add an issue to core.matrix reproducing this info, but I won't be able to provide a PR until next weekend at the soonest...

**Comment by mikera** [comment]
In core.matrix outer product is defined as for tensors, see:

https://en.wikipedia.org/wiki/Outer_product

i.e. a 4D array is expected when you take the outer product of two 2D arrays

**Comment by jlowenz** [comment]
Ok, maybe we can agree the documentation/API needs some work then. The documentation for outer-product does not say it's defined as for tensors... it simply says "outer product of numerical arrays" and gives the traditional vector-vector example (while reasonable, generalization to tensor products is not obvious, given that other tools do not do it). Also, see the section ["tensor product of linear maps"](https://en.wikipedia.org/wiki/Tensor_product#Tensor_product_of_linear_maps) on wikipedia, and note that the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) is the tensor product of the linear maps with a fixed basis (often considered the outer product for matrices). Clatrix _can not (now) support the generalized tensor product_ since the underlying implementation only supports 1D vectors and 2D matrices (in order to accelerate operations with JBLAS). 

I see a few options here (not necessarily mutually exclusive)
- Clatrix only implements vector-vector outer product, and throws an exception for other combinations since the order of the (generalized tensor product) output will exceed 2
- Add a Kronecker product protocol to make the output for vectors and matrices (2D arrays) explicit and to allow clatrix to implement a version of the tensor product for matrices
- Add a general tensor product protocol (clatrix would likely not support this)
- Clarify the documentation of outer product stating it actually implements the generalized tensor product

How does numpy or matlab handle this?
- numpy: outer product flattens any input array and computes the standard vector-vector outer product
  - does not implement a general tensor product (matmul and tensordot are the closest options)
- matlab: does not specify an outer product; uses kronecker tensor product only

So, there could clearly be some confusion here, especially for others coming to core.matrix. How do you want to proceed (particularly with respect to the clatrix implementation?)

**Comment by mikera** [comment]
Hi @jlowenz I made some edits to the documentation for `c.c.m/outer-product` to clarify how the outer product is defined.

To help make the Clatrix implementation work, I have made things work so that you can just return `nil` if the outer-product would be a size that Clatrix can't handle, in which case a default implementation will be used instead. I think this is the best solution given that not all implementations will be able to handle arbitrary nd arrays.

Hope that makes sense? Let me know if you need a new core.matrix release

**Comment by jlowenz** [comment]
Ok, thanks @mikera, I'll modify the clatrix implementation to return `nil` when appropriate (i.e. everything but vector-vector). However, this leaves no "outlet" for the Kronecker product implementation, which would be a useful addition to the c.c.m function set...

**Comment by jlowenz** [comment]
Also - if you make a new release, are you OK with changing the c.c.m version in the clatrix dependencies? Otherwise, I'll need to punt on the outer-product tests, since they'll return `nil`.

**Comment by mikera** [comment]
I'd be happy to take a PR for Knonecker product in `clojure.core.matrix.linear` ns.

I think Clatrix needs a dependency bump, it should be using core.matrix 0.55.0 at least, then is can use the lastest core.matrix compliance test suite. Will take a look at this if I get time this week.

**Comment by jlowenz** [comment]
Closing, since I abandoned this too long ago... :-(

**Pull request closed without merging**
